theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true
true-color = true
idle-timeout = 0
rulers = [80]
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
# left = ["mode", "spinner", "file-name"] # Default
left = ["mode", "spinner", "spacer", "version-control", "spacer", "file-name"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
K = "hover"
G = "goto_last_line"

[keys.normal.g]
c = "toggle_comments"

[keys.normal.space]
w = ":write"
q = ":quit"
"[" = "jump_view_left"
"]" = "jump_view_right"
